CC=g++
HDR=../include
CPPFLAGS=-std=c++11 -D_USE_POOL_ALLOC -g -I $(HDR)


LDLIBS=$(wildcard ../source/*.o)
SRC=$(wildcard *.cpp)
EXE=$(patsubst %.cpp,%,$(SRC))


all: $(EXE)


.PHONY: clean
clean:
	rm -f $(EXE)


echo:
	@echo LDLIBS=$(LDLIBS)
	@echo SRC=$(SRC)  
	@echo CPPFLAGS=$(CPPFLAGS) 
